apiVersion: v1
data:
  ca.pem: |+
    -----BEGIN CERTIFICATE-----
    <put your ca PEM here> 
    -----END CERTIFICATE-----
  rsa_pub: |+
    ssh-rsa  <put your public key here>
kind: ConfigMap
metadata:
  name: trusted-ca-cm
  namespace: cert-manager
---
apiVersion: v1
data:
    build-ca.sh: |+
      #!/usr/bin/env bash 
      set -euxo pipefail
      # cat /etc/host/keys/rsa_pub >> /etc/host/ssh/authorized_keys
      tdnf install -y openssl-c_rehash
      echo "$TRUSTED_CERT" > /etc/ssl/certs/niceneasy-ca.pem
      /usr/bin/rehash_ca_certificates.sh
      grep -qxF '192.168.0.146    harbor.ne.local' /etc/host/hosts || echo "192.168.0.146    harbor.ne.local" >> /etc/host/hosts
      grep -qxF '192.168.0.32     nexus.ne.local' /etc/host/hosts || echo "192.168.0.32     nexus.ne.local" >> /etc/host/hosts
      grep -qxF '192.168.0.137    cmp.niceneasy.ch' /etc/host/hosts || echo "192.168.0.137    cmp.niceneasy.ch" >> /etc/host/hosts
      curl -vv https://cmp.niceneasy.ch
      curl -vv --location --request POST 'http://192.168.0.151:8679/api/restart' --header 'Content-Type: application/json' --data-raw '{
         "ip": "'"$HOST_IP"'",
         "serviceName": "containerd"
      }'
kind: ConfigMap
metadata:
    name: rehash-script
    namespace: cert-manager
---    
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trusted-ca-updater
  namespace: cert-manager
  labels:
    k8s-app: trusted-ca-updater
spec:
  selector:
    matchLabels:
      name: trusted-ca-updater
  template:
    metadata:
      labels:
        name: trusted-ca-updater
    spec:
      serviceAccountName: cert-manager
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      initContainers:
      - name: script-runner
        image: photon:3.0
        command: ["/bin/sh", "-c", "/root/build-ca.sh" ]
        volumeMounts:
        - name: update-trusted-certs-script
          mountPath: /root/
        - name: certs-dir
          mountPath: /etc/ssl/certs
        - name: agg-certs-dir
          mountPath: /etc/pki/tls/certs/
        - name: hosts-file
          mountPath: /etc/host
        - name: ssh-file
          mountPath: /etc/host/ssh
        - name: ssh-keys
          mountPath: /etc/host/keys
        env:
        - name: TRUSTED_CERT
          valueFrom:
            configMapKeyRef:
              name: trusted-ca-cm
              key: ca.pem    
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP              
        resources:
            limits:
              ephemeral-storage: 4G 
      containers:
      - name: sleepy
        image: photon:3.0
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600;done"]
      volumes:
      - name: update-trusted-certs-script
        configMap:
            name: rehash-script
            defaultMode: 0766
      - name: ssh-keys
        configMap:
            name: trusted-ca-cm
            defaultMode: 0600
      - name: certs-dir
        hostPath:
          path: /etc/ssl/certs
          type: Directory
      - name: agg-certs-dir
        hostPath:
          path: /etc/pki/tls/certs/
          type: Directory
      - name: hosts-file
        hostPath:
          path: /etc
          type: Directory
      - name: ssh-file
        hostPath:
          path: /home/vmware-system-user/.ssh
          type: Directory
