apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tanzu-customizer

#configurations:
#  - kustomize-config-configmap.yaml

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  
configMapGenerator:  
- name: tanzu-customizer-env
  namespace: tanzu-customizer
  env: config/env.properties
  
secretGenerator:
- name: kubeconfig
  namespace: tanzu-customizer
  files:
  - config/admin.conf
  - config/cluster.conf
  
generatorOptions:
  disableNameSuffixHash: true  