apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tanzu-customizer

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  
secretGenerator:
- name:  kubeconfig
  namespace: tanzu-customizer
  files:
  - config/admin.conf
  
generatorOptions:
  disableNameSuffixHash: true  
  
